import { GoogleGenerativeAI } from '@google/generative-ai';
import { products } from '../../data/products.js';

const SYSTEM_INSTRUCTION = `You are a friendly, enthusiastic, and professional smart fashion styling assistant for the Fashi clothing store.
Here is the available store inventory with specific sizing, gender targets, and body metrics parameters in JSON format:
${JSON.stringify(products, null, 2)}

CRITICAL RESPONSE AND MATCHING RULES:
1. BODY METRIC FILTERING: When a user shares their gender, height (cm/m), or weight (kg), look closely at the "gender" and "specs" (height/weight ranges) of the products. Recommend ONLY the items that fit their physical profile.
2. SIZE SUGGESTION: Always recommend the best size (S, M, L, XL, XXL) based on their body profile from the "sizes" array.
3. COLOR PREFERENCE: Prioritize items matching the user's preferred color or suggest coordinating products.
4. LANGUAGE: Detect the user's language. Always respond in the same language the user uses (e.g., respond in Vietnamese if they ask in Vietnamese, and respond in English if they ask in English). Maintain a natural, polite, and helpful tone.
5. NO PRODUCT ID TEXT: NEVER write product ID numbers (e.g., 'ID 6', 'sản phẩm 6') in conversational responses.
6. PRODUCT CARD STRUCTURE (FIXED HTML TO PREVENT REACT CRASH): You MUST strictly output the product card using this exact HTML structure with plain HTML attributes (use "class" instead of "className"). Do not put any inner text inside the image div or text tags that conflicts with React's dangerouslySetInnerHTML:
<a href="/product/INSERT_PRODUCT_ID_HERE" class="d-flex align-items-center gap-3 my-2 p-3 bg-white rounded border text-decoration-none text-dark shadow-sm" style="width:100%; box-sizing:border-box; display:flex !important; align-items:center !important; text-align:left !important;">
  <div style="width:55px; height:55px; flex-shrink:0; overflow:hidden;" class="rounded border">
     <img src="/INSERT_IMAGE_PATH_HERE" style="width:100%; height:100%; object-fit:cover;" alt="Product" />
  </div>
  <div class="flex-grow-1" style="line-height:1.4; min-width:0; padding-left:4px;">
     <div class="text-primary fw-bold text-truncate" style="font-size:14px; max-width:100%;" title="INSERT_PRODUCT_NAME_HERE">INSERT_PRODUCT_NAME_HERE</div>
     <div class="text-danger fw-bold mt-1" style="font-size:13px;">INSERT_FORMATTED_PRICE_HEREđ</div>
  </div>
</a>
(Notice: Ensure there is exactly ONE leading slash before the path, formatted precisely as src="/img/products/product-X.jpg").
7. Price formatting: ALWAYS format with thousands separators followed by 'đ' (e.g., 850000 -> "850.000đ").
8. Do NOT use Markdown formatting (like **, *, \`\`\`). Use <br/> for line breaks.
9. Never wrap output HTML in markdown code blocks like \`\`\`html.`;

let chatSession = null;

/**
 * Initializes or returns the existing Gemini chat session.
 * @param {string} apiKey - Google Gemini API Key
 * @param {Array} messages - Chat history list
 * @returns {object} Gemini Chat Session
 */
export function initChatSession(apiKey, messages) {
  if (chatSession) return chatSession;

  if (!apiKey) {
    throw new Error("VITE_GEMINI_API_KEY is not defined in environment variables.");
  }

  const genAI = new GoogleGenerativeAI(apiKey);
  const model = genAI.getGenerativeModel({
    model: 'gemini-2.5-flash',
    systemInstruction: SYSTEM_INSTRUCTION
  });

  const safeMessages = Array.isArray(messages) ? messages : [];
  // Exclude the initial bot greeting message from API context history
  const apiHistory = safeMessages
    .slice(1)
    .filter(msg => msg?.text && msg?.sender)
    .map(msg => ({
      role: msg.sender === 'user' ? 'user' : 'model',
      parts: [{ text: msg.text }]
    }));

  chatSession = model.startChat({
    history: apiHistory,
    generationConfig: { temperature: 0.7 }
  });

  return chatSession;
}

/**
 * Resets the chat session (e.g., when clearing history).
 */
export function resetChatSession() {
  chatSession = null;
}

/**
 * Sends a message to the AI and returns the cleaned text response.
 * @param {string} apiKey - Google Gemini API Key
 * @param {string} messageText - The user message to send
 * @param {Array} messages - The previous message history context
 * @returns {Promise<string>} The response from the AI assistant
 */
export async function sendMessageToAI(apiKey, messageText, messages) {
  const chat = initChatSession(apiKey, messages);
  const result = await chat.sendMessage(messageText);
  let text = await result.response.text();

  // Strip accidental markdown wrapper syntax if generated by the model
  text = text.replace(/```html/g, '').replace(/```/g, '').trim();
  return text;
}
